www:
  build: ./www/.
  ports:
    - "8095:8095"
  env_file: ./www/.env
  environment:
    DATABASE_URL: 'postgres://deepkeep:deepkeep@wwwpostgres:5432/deepkeep'
  links:
    - wwwpostgres
wwwpostgres:
  image: postgres
  environment:
    POSTGRES_USER: 'deepkeep'
    POSTGRES_PASSWORD: 'deepkeep'
dockerregistry:
  image: registry:2
  ports:
    - "5000:5000"
  links:
    - www
  environment:
    REGISTRY_NOTIFICATIONS_ENDPOINTS: [{ name: 'deepkeep-www', url: 'http://www:8095/private/api/v1/dockerevents' }]
