www:
  build: ./www
  ports:
    - "8095:8095"
  env_file: auth0.env
  environment:
    DATABASE_URL: 'postgres://deepkeep:deepkeep@wwwpostgres:5432/deepkeep'
    PORT: 8095
  links:
    - wwwpostgres
wwwpostgres:
  image: postgres
  environment:
    POSTGRES_USER: 'deepkeep'
    POSTGRES_PASSWORD: 'deepkeep'
dockerregistry:
  image: registry:2
  ports:
    - "5000:5000"
  links:
    - www
  environment:
    REGISTRY_NOTIFICATIONS_ENDPOINTS: [{ name: 'deepkeep-www', url: 'http://www:8095/private/api/v1/dockerevents' }]
packagerepository:
  build: ./package-repository
  ports:
    - "8096:8096"
  links:
    - www
  env_file: auth0.env
  environment:
    WEBHOOK_URL: http://www:8095/private/api/v1/packagesevent
